image: guix 
packages:
  - haunt
  - hut
  - guile-commonmark
oauth: pages.sr.ht/PAGES:RW
environment:
  site: awesome.haunt.page
tasks:
- package: |
    cd awesome-haunt-page 
    haunt build
    tar -C site -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz

